### ISSUE TITLE
Mark generated files as read-only in RStudio

### ISSUE THREAD

**Issue by krlmlr** [anthonynorth/roxyglobals#2]
We only need to add the magic words "# Generated by roxyglobals: do not edit by hand" to the first line of the file.

**Comment by anthonynorth** [comment]
Interesting choice of keywords for flagging generated files: [SessionSourceDatabase.cpp](https://github.com/rstudio/rstudio/blob/master/src/cpp/session/SessionSourceDatabase.cpp#L291-L298)
Surely `generated` would have been more appropriate?
