### ISSUE TITLE
Any plans to put roxyglobals on CRAN?

### ISSUE THREAD

**Issue by joelnitta** [anthonynorth/roxyglobals#4]
Thanks for the package! It's great to be able to automate this part of package development.

It seems `roxyglobals` is not on CRAN... do you plan to do that? 

The main reason I ask is because of a note generated by `R CMD check`. When I run `devtools::document()` while using `roxyglobals`, [it adds `roxyglobals (>= 0.2.1)` to `Suggests:` and `anthonynorth/roxyglobals` to `Remotes:` in `DESCRIPTION`](https://github.com/joelnitta/canaper/blob/f3b0fdc5470aa0cc0fc0193578b1074724acf162/DESCRIPTION). 

After this, `R CMD check` issues a NOTE:

```
Unknown, possibly mis-spelled, fields in DESCRIPTION:
    ‘Remotes’
```

Should I just delete `roxyglobals` from `Suggests` and delete `Remotes` entirely when submitting to CRAN? If `roxyglobals` goes onto CRAN, I could keep it in `Suggests`.

**Comment by anthonynorth** [comment]
I hadn't made any plans to release `roxyglobals` on CRAN, however perhaps I should. 

In the meantime, I think you should be able to keep CRAN happy by:
- removing `Remotes` and `roxyglobals` from `Suggests` as you said
- remove `Roxgen` options, reverting to roxygen2 defaults. https://github.com/joelnitta/canaper/blob/f3b0fdc5470aa0cc0fc0193578b1074724acf162/DESCRIPTION#L14-L16

**Comment by joelnitta** [comment]
Thanks! Feel free to close depending on what you decide to do about CRAN submission. I'll let you know/reopen if your suggestions don't work for some reason.

**Comment by anthonynorth** [comment]
I have to correct myself; removing the Roxygen options -- and thus disabling roxyglobals, which I failed to mention -- shouldn't actually be necessary. If roxyglobals isn't "registered" (for the lack of a better term), you'll need to specify it manually in `devtools::document(roclets = c())`, which isn't ideal.

It looks as though `R CMD check --as-cran` doesn't trigger `roxygen2::roxygenise()`, so this block should make no difference on CRAN (I think).

```
Roxygen: list(
    markdown = TRUE,
    roclets = c("collate", "namespace", "rd", "roxyglobals::global_roclet"))
```

**Comment by jangorecki** [comment]
+1
I am working on a package that uses roxyglobals, and would appreciate if it would land on CRAN.

**Comment by anthonynorth** [comment]
Submitted to CRAN :crossed_fingers:
